name: 'weather_project'
version: '1.0'
config-version: 2
profile: 'weather_project'

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

models:
  weather_project:
    staging:
      +schema: STAGING
    marts:
      +schema: DWH
